define([], function() {
  return {
    "HeroTitle": "Welcome to the Event!",
    "HeroDescription": "Share your feedback below.",
    "SendButton": "Send Feedback",
    "ConsultComments": "Consult Comments",
    "Dashboard": "Dashboard",
    "Inicio": "Home",
    "EnviarComentario": "Send Comment",
    "FeedbackFormTitle": "Send a New Comment",
    "FeedbackPlaceholder": "Write your comment here...",
    "FeedbackSuccess": "Comment sent successfully!",
    "FeedbackError": "Error saving the comment in SharePoint.",
    "DashboardTitle": "Interactive Dashboard",
    "FilterAll": "All",
    "FilterPositive": "Positive",
    "FilterNegative": "Negative",
    "FilterNeutral": "Neutral",
    "Recent": "Recent",
    "Oldest": "Oldest",
    "ChartDescSentiment": "View the proportion of positive, negative, and neutral comments received. This chart helps you quickly identify the overall sentiment of your audience regarding your products or services.",
    "ChartDescMonthly": "See how the number of each sentiment type changes over the months. Useful for spotting trends, evaluating campaign impact, and anticipating shifts in public perception.",
    "ChartDescVolume": "Check the total volume of comments received per month. This chart helps identify participation spikes and relate them to events, launches, or specific actions.",
    "ChartDescKeyphrases": "Discover which keywords are most mentioned by your audience in their comments. This helps you identify the topics, products, or concepts that generate the most interest or concern.",
    "PropertyPaneDescription": "Configure your feedback web part",
    "BasicGroupName": "General Settings",
    "HeroTitleLabel": "Hero Title",
    "HeroDescriptionLabel": "Hero Description",
    "HeroButtonTextLabel": "Button Text",
    "FeedbackListNameLabel": "SharePoint List Name",
    "AnalystGroupNameLabel": "Analyst Group Name",
    "AppLocalEnvironmentSharePoint": "The app is running on your local environment as SharePoint web part",
    "AppLocalEnvironmentTeams": "The app is running on your local environment as Microsoft Teams app",
    "AppLocalEnvironmentOffice": "The app is running on your local environment in office.com",
    "AppLocalEnvironmentOutlook": "The app is running on your local environment in Outlook",
    "AppSharePointEnvironment": "The app is running on SharePoint page",
    "AppTeamsTabEnvironment": "The app is running in Microsoft Teams",
    "AppOfficeEnvironment": "The app is running in office.com",
    "AppOutlookEnvironment": "The app is running in Outlook",
    "UnknownEnvironment": "The app is running in an unknown environment"
  }
});